"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Alert } from "@/components/ui/state";
import { createSupabaseBrowserClient } from "@/lib/supabase/browser";

export function RegisterForm() {
  const router = useRouter(); const [fullName, setFullName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [errorMessage, setErrorMessage] = useState(""); const [successMessage, setSuccessMessage] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setErrorMessage(""); setSuccessMessage(""); const name = fullName.trim(), address = email.trim(); if (!name || !address || !password || !confirm) { setErrorMessage("Complete every field to create your account."); return; } if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(address)) { setErrorMessage("Enter a valid email address."); return; } if (password.length < 8) { setErrorMessage("Choose a password with at least 8 characters."); return; } if (password !== confirm) { setErrorMessage("Your passwords do not match."); return; } setLoading(true); const { data, error } = await createSupabaseBrowserClient().auth.signUp({ email: address, password, options: { data: { full_name: name }, emailRedirectTo: `${window.location.origin}/auth/callback?next=/dashboard` } }); setLoading(false); if (error) { setErrorMessage("We could not create your account. Please try again later."); return; } if (data.session) { router.replace("/dashboard"); router.refresh(); return; } setSuccessMessage("Check your email to confirm your account, then return here to sign in."); }
  return <form className="auth-card auth-form" onSubmit={submit}><p className="auth-form__intro">Create an account for structured CBT practice and result review.</p><label>Full name<input autoComplete="name" value={fullName} onChange={event => setFullName(event.target.value)} required maxLength={120} disabled={loading} /></label><label>Email address<input type="email" autoComplete="email" value={email} onChange={event => setEmail(event.target.value)} required disabled={loading} /></label><label>Password<input type="password" autoComplete="new-password" value={password} onChange={event => setPassword(event.target.value)} required minLength={8} disabled={loading} /><small>Use at least 8 characters.</small></label><label>Confirm password<input type="password" autoComplete="new-password" value={confirm} onChange={event => setConfirm(event.target.value)} required minLength={8} disabled={loading} /></label><button className="btn btn-primary" disabled={loading}>{loading ? "Creating account..." : "Create account"}</button>{errorMessage ? <Alert tone="error" title="Unable to create account">{errorMessage}</Alert> : null}{successMessage ? <Alert tone="success" title="Check your inbox">{successMessage}</Alert> : null}</form>;
}
