import { createClient } from "@supabase/supabase-js";
import { loadEnvConfig } from "@next/env";
import { LEGACY_QUESTIONS_BY_SUBJECT } from "@/data/legacy-question-bank";
loadEnvConfig(process.cwd());
const SUBJECT_ID="a55ad82b-4630-491b-ae8d-76613c147d27";
const range=(a:number,b:number)=>Array.from({length:b-a+1},(_,i)=>`ECO${a+i}`);
const ARCHIVE=new Set(["ECO85","ECO86","ECO87","ECO88","ECO89","ECO93","ECO94","ECO95","ECO102","ECO109","ECO110","ECO111","ECO112","ECO113","ECO114","ECO116","ECO119"]);
const groups:Record<string,string[]>={
 "Basic Economic Problems, Demand and Supply":["ECO1","ECO2","ECO3","ECO13","ECO14","ECO15","ECO22","ECO23"],
 "Elasticity, Utility and Consumer Equilibrium":range(4,12).concat(range(16,21)),
 "Costs, Production Possibility and Scale":range(24,29).concat(range(38,40)),"Market Structures and Profit":range(30,37),
 "National Income, Inflation and Unemployment":range(41,52),"Fiscal and Monetary Policy":range(53,60).concat(range(69,75)),
 "Nigerian Economy and Economic Institutions":range(76,84).concat(range(90,92)).concat(range(96,101)).concat(range(103,108)).concat(["ECO115","ECO117","ECO118","ECO120"]),
 "Balance of Payments and Foreign Exchange":range(61,68).concat(range(139,145)),"International Trade and Economic Integration":range(121,138).concat(range(146,160)),
 "Economic Growth, Poverty and Development Theory":range(161,180).concat(range(183,198)),"Population, Sustainability and Development Challenges":["ECO181","ECO182","ECO199","ECO200"]};
const medium=new Set([...range(4,15),...range(16,40),...range(53,75),...range(121,200)]);
async function main(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL||process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error('Supabase URL and service-role key are required.');const db=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});const source=(LEGACY_QUESTIONS_BY_SUBJECT as Record<string,unknown[]>).Economics??[];if(source.length!==200)throw new Error('Expected 200 Economics source records.');const ts=await db.from('topics').select('id,name').eq('subject_id',SUBJECT_ID);if(ts.error)throw ts.error;const names=new Map((ts.data??[]).map(x=>[x.name,x.id])),m=new Map<string,string>();for(const [name,ids] of Object.entries(groups)){const tid=names.get(name);if(!tid)throw new Error(`Missing topic ${name}`);for(const x of ids){if(m.has(x))throw new Error(`Duplicate mapping ${x}`);m.set(x,tid)}}const qs=await db.from('questions').select('id,legacy_id,is_active,topic_id,difficulty').eq('subject_id',SUBJECT_ID);if(qs.error)throw qs.error;let archived=0,updated=0;for(const q of qs.data??[]){const off=ARCHIVE.has(q.legacy_id),tid=m.get(q.legacy_id);if(!off&&!tid)throw new Error(`No reviewed mapping for ${q.legacy_id}`);const next={is_active:!off,topic_id:off?null:tid,difficulty:off?null:(medium.has(q.legacy_id)?'medium':'easy')};if(q.is_active!==next.is_active||q.topic_id!==next.topic_id||q.difficulty!==next.difficulty){const r=await db.from('questions').update(next).eq('id',q.id);if(r.error)throw r.error;if(off)archived++;else updated++}}const f=await db.from('questions').select('topic_id,difficulty').eq('subject_id',SUBJECT_ID).eq('is_active',true);if(f.error)throw f.error;console.log(JSON.stringify({sourceCount:source.length,archived,updated,active:f.data?.length??0,unassigned:(f.data??[]).filter(x=>!x.topic_id).length,difficulty:Object.fromEntries(['easy','medium','hard'].map(x=>[x,(f.data??[]).filter(q=>q.difficulty===x).length]))},null,2))}main().catch(e=>{console.error('Economics remediation failed:',e);process.exit(1)});
